server:
  port: 8080
#====================================stream =============================================
spring:
  application:
    name: seata-dubbo-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#====================================Dubbo config===============================================
dubbo:
  application:
    name: ${spring.application.name}
    qosEnable: false
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: "com.phper666.seata.test.web"
  cloud:
    subscribed-services: ${spring.application.name}

#====================================Seata Config===============================================
seata:
  enabled: true
  # 设置为false，使用TCC，true为使用AT
  enable-auto-data-source-proxy: false
  application-id: ${spring.application.name}
  tx-service-group: tx_service_group_test # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  #  client:
  #    rm-report-success-enable: true
  #    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
  #    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
  #    rm-async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
  #    rm:
  #      lock:
  #        lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
  #        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
  #        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
  #    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
  #    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
  #    undo:
  #      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
  #      undo-log-serialization: jackson # undo序列化方式（默认jackson）
  #      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
  #    support:
  #      spring:
  #        datasource-autoproxy: true
  #  service:
  #    vgroup-mapping:
  #      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
  #    enable-degrade: false # 降级开关
  #    disable-global-transaction: false # 禁用全局事务（默认false）
  #    grouplist:
  #      default: localhost:8091
  #  transport:
  #    shutdown:
  #      wait: 3
  #    thread-factory:
  #      boss-thread-prefix: NettyBoss
  #      worker-thread-prefix: NettyServerNIOWorker
  #      server-executor-thread-prefix: NettyServerBizHandler
  #      share-boss-worker: false
  #      client-selector-thread-prefix: NettyClientSelector
  #      client-selector-thread-size: 1
  #      client-worker-thread-prefix: NettyClientWorkerThread
  #    type: TCP
  #    server: NIO
  #    heartbeat: true
  #    serialization: seata
  #    compressor: none
  #    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  #  registry:
  #    type: nacos
  #    nacos:
  #      server-addr: localhost:8848
  #      namespace: seataid
  #      cluster: default
  #      username: nacos
  #      password: nacos
  #      group:
  #  config:
  #    type: nacos
  #    nacos:
  #      namespace: seataid
  #      server-addr: localhost:8848
  #      username: nacos
  #      password: nacos
  #      data-id: seata-service.properties
  #      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 9fdcbe8r-4511-4a30-b5f0-7a4fab022ac7
      group: seata-server
      cluster: default
  config:
    type: nacos
    nacos:
      namespace: 9fdcbe8r-4511-4a30-b5f0-7a4fab022ac7
      server-addr: localhost:8848
      data-id: seata.properties
      group: seata-server
  log:
    exception-rate: 100
